import type { Metadata } from "next";
import "./global.css";
import { Noto_Sans_KR } from "next/font/google";

export const sans = Noto_Sans_KR({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={sans.className}>{children}</body>
    </html>
  );
}
